apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::733818669583:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NN4XGEC18LM2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::733818669583:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-05T05:23:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1438"
  uid: 4ff98390-a440-41c7-80aa-814ddf345319
